Continue rename in bin

diff --git a/bin/init.d/alignak b/bin/init.d/alignak
--- a/bin/init.d/alignak
+++ b/bin/init.d/alignak
@@ -1,34 +1,55 @@
 #!/bin/sh
-
-# Copyright (C) 2009-2014:
-#    Gabes Jean, naparuba@gmail.com
-#    Gerhard Lausser, Gerhard.Lausser@consol.de
-#    Gregory Starck, g.starck@gmail.com
-#    Hartmut Goebel, h.goebel@goebel-consult.de
 #
-# This file is part of Shinken.
+# Copyright (C) 2015-2015: Alignak team, see AUTHORS.txt file for contributors
 #
-# Shinken is free software: you can redistribute it and/or modify
+# This file is part of Alignak.
+#
+# Alignak is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
-# Shinken is distributed in the hope that it will be useful,
+# Alignak is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Affero General Public License for more details.
 #
 # You should have received a copy of the GNU Affero General Public License
-# along with Shinken.  If not, see <http://www.gnu.org/licenses/>.
+# along with Alignak.  If not, see <http://www.gnu.org/licenses/>.
+#
+#
+# This file incorporates work covered by the following copyright and
+# permission notice:
+#
+#  Copyright (C) 2009-2014:
+#     Gabes Jean, naparuba@gmail.com
+#     Gerhard Lausser, Gerhard.Lausser@consol.de
+#     Gregory Starck, g.starck@gmail.com
+#     Hartmut Goebel, h.goebel@goebel-consult.de
+#
+#  This file is part of Shinken.
+#
+#  Shinken is free software: you can redistribute it and/or modify
+#  it under the terms of the GNU Affero General Public License as published by
+#  the Free Software Foundation, either version 3 of the License, or
+#  (at your option) any later version.
+#
+#  Shinken is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU Affero General Public License for more details.
+#
+#  You should have received a copy of the GNU Affero General Public License
+#  along with Shinken.  If not, see <http://www.gnu.org/licenses/>.
 
 ### BEGIN INIT INFO
-# Provides:          shinken
+# Provides:          alignak
 # Required-Start:    $network $remote_fs
 # Required-Stop:     $network $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Shinken monitoring daemon
-# Description:       Shinken is a monitoring tool composed of many separated modules:
+# Short-Description: alignak monitoring daemon
+# Description:       alignak is a monitoring tool composed of many separated modules:
 #     - arbiter     : the main one : control everything else.
 #     - scheduler   : receives checks/actions from arbiter. Schedules & forwards them to pollers.
 #     - poller      : receives the checks from a scheduler. Launch them and returns results
@@ -38,25 +59,25 @@
 ### END INIT INFO
 
 ### Chkconfig Header
-# Shinken        Starts Shinken daemons
+# Alignak        Starts Alignak daemons
 #
 # chkconfig: 345 99 01
-# description: Start Shinken daemons
+# description: Start Alignak daemons
 
 # Reference:
 # http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
 
 
-NAME="shinken"
+NAME="alignak"
 
 AVAIL_MODULES="scheduler poller reactionner broker receiver arbiter"
 
-## SHINKEN_MODULE_FILE is set by shinken-* if it's one of these that's calling us.
-if [ -z "$SHINKEN_MODULE_FILE" ]; then
+## ALIGNAK_MODULE_FILE is set by alignak-* if it's one of these that's calling us.
+if [ -z "$ALIGNAK_MODULE_FILE" ]; then
     SCRIPTNAME=$0
     _usage_mods_="[ <$AVAIL_MODULES> ]"
 else
-    SCRIPTNAME=$SHINKEN_MODULE_FILE
+    SCRIPTNAME=$ALIGNAK_MODULE_FILE
 fi
 
 curpath=$(cd $(dirname "$0") && pwd)
@@ -109,9 +130,9 @@ pythonver() {
 # Ok, go search this Python version
 pythonver
 
-# Uncomment the line below if you got the **lib** shinken installed
+# Uncomment the line below if you got the **lib** alignak installed
 # on a non standard place (not in /usr/lib/python*)
-#export PYTHONPATH="${PATH:+$PATH:}/opt/shinken"
+#export PYTHONPATH="${PATH:+$PATH:}/opt/alignak"
 # Or uncommentif you want to force the Python version
 #export PYTHON=python2.7
 
@@ -120,13 +141,13 @@ DEBUG=false
 CMD=""
 SUBMODULES=""
 
-## This permits to overhidde the default "default shinken cfg file":
-[ -z "$SHINKEN_DEFAULT_FILE" ] && SHINKEN_DEFAULT_FILE="/etc/default/$NAME"
+## This permits to overhidde the default "default alignak cfg file":
+[ -z "$ALIGNAK_DEFAULT_FILE" ] && ALIGNAK_DEFAULT_FILE="/etc/default/$NAME"
 ## so you can now do:
-## bash -c "SHINKEN_DEFAULT_FILE=$your_own_default_file $init_path/shinken $action $args"
+## bash -c "ALIGNAK_DEFAULT_FILE=$your_own_default_file $init_path/alignak $action $args"
 ## to easily use your own config
 
-#echo "Using $SHINKEN_DEFAULT_FILE .."
+#echo "Using $ALIGNAK_DEFAULT_FILE .."
 
 
 
@@ -154,7 +175,7 @@ shift
 SUBMODULES=$*
 
 # Reads configuration variable file if it is present
-[ -r "$SHINKEN_DEFAULT_FILE" ] && . "$SHINKEN_DEFAULT_FILE"
+[ -r "$ALIGNAK_DEFAULT_FILE" ] && . "$ALIGNAK_DEFAULT_FILE"
 
 if [ -z "$SUBMODULES" ]; then
     SUBMODULES=$AVAIL_MODULES
@@ -170,14 +191,14 @@ else
 fi
 
 # Now look if some required variables are pre defined:
-if ! test "$SHINKENCFG"
+if ! test "$ALIGNAKCFG"
 then
-    SHINKENCFG="$ETC/shinken.cfg"
+    ALIGNAKCFG="$ETC/alignak.cfg"
 fi
 
 # If var or run dir is missing, create them and chown them
-[ ! -d $VAR ] && mkdir -p $VAR && chown $SHINKENUSER:$SHINKENGROUP $VAR
-[ ! -d $RUN ] && mkdir -p $RUN && chown $SHINKENUSER:$SHINKENGROUP $RUN
+[ ! -d $VAR ] && mkdir -p $VAR && chown $ALIGNAKUSER:$ALIGNAKGROUP $VAR
+[ ! -d $RUN ] && mkdir -p $RUN && chown $ALIGNAKUSER:$ALIGNAKGROUP $RUN
 
 # Now place us in our var directory so even our arbiter will be
 # happy for opening its pid and cmd files
@@ -284,24 +305,24 @@ do_status() {
 #
 do_start() {
     mod=$1
-    modfilepath="$BIN/shinken-${mod}"
+    modfilepath="$BIN/alignak-${mod}"
     [ -e "$modfilepath" ] || {
-        log_failure_msg "FAILED: did not find $mod file ($modfilepath) ; are you sure shinken-$mod is installed?"
+        log_failure_msg "FAILED: did not find $mod file ($modfilepath) ; are you sure alignak-$mod is installed?"
         return 5
     }
     [ "$DEBUG" = 1 ] && DEBUGCMD="--debug "$(getdebugfile "$mod")
-    # Arbiter shinken.cfg, and the other OTHERd.ini
+    # Arbiter alignak.cfg, and the other OTHERd.ini
     if [ "$mod" != "arbiter" ]; then
         modINI=$(echo "$"${mod}CFG | tr '[:lower:]' '[:upper:]')
         modinifile=$(eval echo ${modINI})
         output=$($PYTHON "$modfilepath" -d -c "${modinifile}" $DEBUGCMD 2>&1)
         rc=$?
     else
-        if ! test "$SHINKENSPECIFICCFG"
+        if ! test "$ALIGNAKSPECIFICCFG"
         then
-            output=$($PYTHON "$modfilepath" -d -c "$SHINKENCFG" $DEBUGCMD 2>&1)
+            output=$($PYTHON "$modfilepath" -d -c "$ALIGNAKCFG" $DEBUGCMD 2>&1)
         else
-            output=$($PYTHON "$modfilepath" -d -c "$SHINKENCFG" -c "$SHINKENSPECIFICCFG" $DEBUGCMD 2>&1)
+            output=$($PYTHON "$modfilepath" -d -c "$ALIGNAKCFG" -c "$ALIGNAKSPECIFICCFG" $DEBUGCMD 2>&1)
         fi
         rc=$?
     fi
@@ -337,7 +358,7 @@ do_stop() {
         for i in 1 2 3
         do
             # TODO: use a better way to get the children pids..
-            allpids="$(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}')"
+            allpids="$(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}')"
             if [ -z "$allpids" ]; then
                 echo "OK"
                 return 0
@@ -345,14 +366,14 @@ do_stop() {
             sleep 1
         done
         echo "there are still remaining processes to $mod running.. ; trying to kill them (SIGTERM).."
-        allpids="$(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}')"
-        for cpid in $(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}'); do
+        allpids="$(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}')"
+        for cpid in $(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}'); do
             kill $cpid > /dev/null 2>&1
         done
         for i in 1 2 3
         do
             # TODO: eventually use a better way to get the children pids..
-            allpids="$(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}')"
+            allpids="$(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}')"
             if [ -z "$allpids" ]; then
                 echo "OK"
                 return 0
@@ -360,12 +381,12 @@ do_stop() {
             sleep 1
         done
         echo "there are still remaining processes to $mod running.. ; trying to kill -9 them.."
-        allpids="$(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}')"
-        for cpid in $(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}'); do
+        allpids="$(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}')"
+        for cpid in $(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}'); do
             kill -9 $cpid > /dev/null 2>&1
         done
         sleep 1
-        allpids="$(ps -aef | grep "$pid" | grep "shinken-$mod" | awk '{print $2}')"
+        allpids="$(ps -aef | grep "$pid" | grep "alignak-$mod" | awk '{print $2}')"
         if [ ! -z "$allpids" ]; then
             echo "FAILED: one or more process for $mod are still running after kill -9!"
             echo "Remaining processes are (pids="$allpids"):"
@@ -385,11 +406,11 @@ do_stop() {
 #
 do_check() {
     [ "$DEBUG" = 1 ] && DEBUGCMD="--debug $VAR/${mod}-debug.log"
-    if ! test "$SHINKENSPECIFICCFG"
+    if ! test "$ALIGNAKSPECIFICCFG"
     then
-       $PYTHON "$BIN/shinken-arbiter" -v -c "$SHINKENCFG" $DEBUGCMD 2>&1
+       $PYTHON "$BIN/alignak-arbiter" -v -c "$ALIGNAKCFG" $DEBUGCMD 2>&1
     else
-       $PYTHON "$BIN/shinken-arbiter" -v -c "$SHINKENCFG" -c "$SHINKENSPECIFICCFG" $DEBUGCMD 2>&1
+       $PYTHON "$BIN/alignak-arbiter" -v -c "$ALIGNAKCFG" -c "$ALIGNAKSPECIFICCFG" $DEBUGCMD 2>&1
     fi
     return $?
 }
@@ -414,7 +435,7 @@ do_start_() {
         # will be created at the correct place.
         cd "$VAR"
         # TODO: check if other possibility wouldn't be better:
-        # declare a "workdir" properties for the arbiter module definition.. in shinken-specific.cfg.
+        # declare a "workdir" properties for the arbiter module definition.. in alignak-specific.cfg.
         # but if the lock_file path is absolute then this 'cd' isn't required.
     fi
     startoutput=$(do_start "$1")
@@ -513,10 +534,10 @@ do_check_() {
     echo "Doing config check"
     output=$(do_check "$1" 2>&1)
     rc=$?
-    check_res_file=$(mktemp /tmp/shinken_checkconfig_resultXXXXXXXX)
+    check_res_file=$(mktemp /tmp/alignak_checkconfig_resultXXXXXXXX)
     echo "$output" > "$check_res_file"
-    mv $check_res_file /tmp/shinken_checkconfig_result
-    check_res_file="/tmp/shinken_checkconfig_result"
+    mv $check_res_file /tmp/alignak_checkconfig_result
+    check_res_file="/tmp/alignak_checkconfig_result"
 
     if [ $rc -eq 0 ]; then
         echo_success
